### ISSUE TITLE
Java Socket throwing IOException when nothing is received

### ISSUE THREAD

**Issue by yunspace** [niwinz/jnanomsg#17]
Hi, thanks for putting together such as neat library. 

I've been trying to use the Java version and I noticed that both `recvBytes()` and `recv()` all throw `IOException` when nothing is received:

https://github.com/niwinz/jnanomsg/blob/master/src/java/nanomsg/Socket.java#L177
https://github.com/niwinz/jnanomsg/blob/master/src/java/nanomsg/Socket.java#L213

This would result in an echo server that looks like this:

    while (true) {
        try {
            byte[] receivedData = sock.recvBytes();
            sock.send(receivedData);
        } catch (IOException iox) {
            System.err.println("nothing received");
        }
    }

Otherwise the while loop would exit with the following error message on the first receive:

    Exception in thread "main" nanomsg.exceptions.IOException: Resource temporarily unavailable
	at nanomsg.Socket.recvBytes(Socket.java:177)
	at nanomsg.Socket.recvString(Socket.java:142)
	at au.com.republicwealth.nano.reqrep.EchoServer.main(EchoServer.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

This is different the expected behaviour according to the `jnanomsg` [docs](http://niwinz.github.io/jnanomsg/latest/#_socket_types_2). This is by design? Or maybe certain status codes such as `Resource temporarily unavailable` should be ommited from throwing `IOException`?

**Comment by niwinz** [comment]
Very strange. It should not do that...

**Comment by 9il** [comment]
> Very strange. It should not do that...

:-)

``` D
  public AbstractSocket(final Domain domain, final SocketType protocol) {
    this.fd = nn_socket(domain.value(), protocol.value());
    this.open = true;

    this.setSocketOpt(SocketOption.NN_SNDTIMEO, 600);
    this.setSocketOpt(SocketOption.NN_RCVTIMEO, 600);
  }
```

**Comment by duhmojo** [comment]
Same problem here. I'm on an Ubuntu 16.04 system running the latest jnanomsg.

        	sock = new SubSocket();
		sock.connect("ipc:///tmp/pubsub.ipc");
		sock.subscribe("TOPIC");
		sock.setRecvTimeout(1000);

		// Later...
		while(true) {
			byte[] rxBytes = null;
			try {
				rxBytes = sock.recvBytes();
				// Do something...
			} catch (IOException ioe) {
				// Doesn't block, throws IOException with message "Resource temporarily unavailable"
			}
		}

In the same application I setup the publisher before the subscriber:

		PubSocket sock = new PubSocket();
		// ...
		sock.bind("ipc:///tmp/pubsub.ipc");
		// Later...
		sock.send("TOPIC " + someJsonString);

Any clues? Thanks.

**Comment by duhmojo** [comment]
So I noticed that jnanomsg 0.4.3 is not the version in the git repo. e.g. the socket refactor isn't in place, which was included in 9il's reply. I cloned, added a new project in Eclipse, made a couple of changes and same issue. e.g. "Resource temporarily unavailable". 

Also, dumb idea, I tried executing as root in case for some reason there was a user related permission problem.

**Comment by snakevash** [comment]
thanks.

Clojure bind have same problem.

**Comment by senses1** [comment]
I have encountered this problem too! would this be fixed?
` @Test
  public void subscribe() {
    final SubSocket socket = new SubSocket();
    socket.connect(ipc://testpub.ipc");
    socket.subscribe("");
    socket.setSocketOpt(Nanomsg.SocketOption.NN_SUB_SUBSCRIBE,"");

    //EnumSet<Nanomsg.SocketFlag> flagSet = EnumSet.of(Nanomsg.SocketFlag.NN_DONTWAIT);
    byte ret[] = new byte[1000] ;
    //ByteBuffer bb = socket.recv(flagSet);
    ByteBuffer bb = socket.recv();
    bb.flip();
    bb.get(ret);

    System.out.println("recv" + ret.toString() );

  }`
the result is 

 com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 nanomsg.NanomsgTest,subscribe
Connected to the target VM, address: '127.0.0.1:33288', transport: 'socket'

nanomsg.exceptions.IOException: Timed out

	at nanomsg.Nanomsg.handleError(Nanomsg.java:35)
	at nanomsg.AbstractSocket.recv(AbstractSocket.java:151)
	at nanomsg.AbstractSocket.recv(AbstractSocket.java:161)
	at nanomsg.NanomsgTest.subscribe(NanomsgTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

Disconnected from the target VM, address: '127.0.0.1:33288', transport: 'socket'`
