### ISSUE TITLE
IllegalArgumentException when subscribe all topics

### ISSUE THREAD

**Issue by mingfai** [niwinz/jnanomsg#5]
when use "" (or new byte[0] in my PR), it shows: 

```
java.lang.IllegalArgumentException: Allocation size must be greater than zero
```

**Comment by evacchi** [comment]
unfortunately this looks still broken in 0.4.1

```java
        SubSocket sock = new SubSocket();
        sock.connect(...);
        sock.subscribe("");

Exception in thread "main" java.lang.IllegalArgumentException: Allocation size must be greater than zero
	at com.sun.jna.Memory.<init>(Memory.java:87)
	at nanomsg.pubsub.SubSocket.subscribe(SubSocket.java:41)
	at nanomsg.pubsub.SubSocket.subscribe(SubSocket.java:54)
	at nanomsg.pubsub.SubSocket.subscribe(SubSocket.java:31)
	...
```

**Comment by evacchi** [comment]
see pull #15
